### PR TITLE
support additional source for webp for cover/content images

### PR DESCRIPTION
**Pull request by provos**
Best practices for web images is to organize them inside a picture tag and provide web optimized image formats.

Since Hugo now natively supports webp, this change wraps an image into a picture tag and provides an additional set of webp sources. The gallery css is moved from the img tag to the picture tag which required a small change to the gallery typescript.

You can check an example page that uses this at: https://www.provos.org/p/finetuning-stable-diffusion-part2/

Ps: This does not check whether the original image is webp already

### CODE REVIEW

**Comment by CaiJimmy** [comment]
Thank you so much for submitting your pull request!

Sorry for the late reply. Unfortunately, I'm still tied up with academic tasks and won't be able to review pull requests for the time being.

Once I have more time, I'll take a look at your pull request and provide feedback.

Thank you again for your contributions!

**Comment by CaiJimmy** [comment]
Thanks for the pull request and sorry for the late response!

This is definitely a nice thing. But with this PR, each image is resized 4 times, resulting in 5 images (including the original).

I think we could just include `srcset` for the WebP format, since it's widely supported, and fall back to the original image in the worst case. (So only 2 resizes will be done, as it was)

What do you think?

----

And here's my `render-image.html` after making such change:

```html
{{- $image := .Page.Resources.GetMatch (printf "%s" (.Destination | safeURL)) -}}
{{- $Permalink := .Destination | relURL | safeURL -}}
{{- $alt := .PlainText | safeHTML -}}
{{- $Width := 0 -}}
{{- $Height := 0 -}}
{{- $Srcset := "" -}}

{{/* SVG and external images won't work with gallery layout, because their width and height attributes are unknown */}}
{{- $galleryImage := false -}}

{{- if $image -}}
	{{- $notSVG := ne (path.Ext .Destination) ".svg" -}}
	{{- $Permalink = $image.RelPermalink -}}

	{{- if $notSVG -}}
		{{- $Width = $image.Width -}}
		{{- $Height = $image.Height -}}
		{{- $galleryImage = true -}}

		{{- if (default true .Page.Site.Params.imageProcessing.content.enabled) -}}
			{{- $small := $image.Resize `webp 480x` -}}
			{{- $big := $image.Resize `webp 1024x` -}}
			{{- $Srcset = printf `%s 480w, %s 1024w` $small.RelPermalink $big.RelPermalink -}}
		{{- end -}}
	{{- end -}}
{{- end -}}

<picture
	{{ if $galleryImage }}
		class="gallery-image" 
		data-flex-grow="{{ div (mul $image.Width 100) $image.Height }}"
		data-flex-basis="{{ div (mul $image.Width 240) $image.Height }}px"
	{{ end }}
>
	{{ with $Srcset }}
		<source type="image/webp"
			srcset="{{ $Srcset }}"
		>
	{{ end }}
	<img src="{{ $Permalink }}"
		{{ with $Width }}width="{{ . }}"{{ end }}
		{{ with $Height }}height="{{ . }}"{{ end }}
		loading="lazy"
		decoding="async"
		{{ with $alt }}
			alt="{{ . }}"
		{{ end }}
	>
</picture>
```

**Review by CaiJimmy — CHANGES_REQUESTED** [review]
Thanks for the pull request and sorry for the late response!

This is definitely a nice thing. But with this PR, each image is resized 4 times, resulting in 5 images (including the original).

I think we could just include `srcset` for the WebP format, since it's widely supported, and fall back to the original image in the worst case. (So only 2 resizes will be done, as it was)

What do you think?

----

And here's my `render-image.html` after making such change:

```html
{{- $image := .Page.Resources.GetMatch (printf "%s" (.Destination | safeURL)) -}}
{{- $Permalink := .Destination | relURL | safeURL -}}
{{- $alt := .PlainText | safeHTML -}}
{{- $Width := 0 -}}
{{- $Height := 0 -}}
{{- $Srcset := "" -}}

{{/* SVG and external images won't work with gallery layout, because their width and height attributes are unknown */}}
{{- $galleryImage := false -}}

{{- if $image -}}
	{{- $notSVG := ne (path.Ext .Destination) ".svg" -}}
	{{- $Permalink = $image.RelPermalink -}}

	{{- if $notSVG -}}
		{{- $Width = $image.Width -}}
		{{- $Height = $image.Height -}}
		{{- $galleryImage = true -}}

		{{- if (default true .Page.Site.Params.imageProcessing.content.enabled) -}}
			{{- $small := $image.Resize `webp 480x` -}}
			{{- $big := $image.Resize `webp 1024x` -}}
			{{- $Srcset = printf `%s 480w, %s 1024w` $small.RelPermalink $big.RelPermalink -}}
		{{- end -}}
	{{- end -}}
{{- end -}}

<picture
	{{ if $galleryImage }}
		class="gallery-image" 
		data-flex-grow="{{ div (mul $image.Width 100) $image.Height }}"
		data-flex-basis="{{ div (mul $image.Width 240) $image.Height }}px"
	{{ end }}
>
	{{ with $Srcset }}
		<source type="image/webp"
			srcset="{{ $Srcset }}"
		>
	{{ end }}
	<img src="{{ $Permalink }}"
		{{ with $Width }}width="{{ . }}"{{ end }}
		{{ with $Height }}height="{{ . }}"{{ end }}
		loading="lazy"
		decoding="async"
		{{ with $alt }}
			alt="{{ . }}"
		{{ end }}
	>
</picture>
```

**Comment by CaiJimmy** [comment]
And the additional reason is that if a browser does not support WebP, it's highly probable that it does not support srcset either.

image

**Comment by provos** [comment]
I agree with you.

When I originally implemented this I was worried about backwards
compatibility. I believe almost every browser supports webp now and the
additional complication is not needed.

Niels.

**Comment by ottok** [comment]
Can you @provos please rebase this on latest upstream git head? I could test it on my website to see how well it works with various browsers etc, and thus provide additional evidence that this should be merged.

[PageSpeed](https://pagespeed.web.dev/) nags on my site that webp would be better for all my images (now jpg/png) and also that I should use webm instead of animated gifs. Additionally PageSpeed does not like that all images have `loading="lazy"`, even the ones above the fold, I this PR would also change that to `decoding=async` which may be better with modern browsers.

**Comment by ottok** [comment]
I tried testing this but mainline has diverged so much that the patch does not apply directly, and my [attempts](https://github.com/ottok/hugo-theme-stack/commit/24c2826e0abbe46d4569ce3df35ea393e053ea28) to apply it manually failed on `parse failed: template: _default/_markup/render-image.html:71: unexpected EOF` and I didn't figure out which of the conditionals has a mismatch..

**Comment by ottok** [comment]
@CaiJimmy May I ask why you merged this on master? The point of a PR is to propose that a new branch is merged into master. Merging that proposed branch on master inside the PR seems to go against that idea. Perhaps you intended to rebase?

image

The PR is based on code from commit 4272da7e from December 2022. If it was rebased, the history would be linear. Now the history is non-linear, and the gif below shows what non-linearity means:

non-linear-history-demonstration

**Comment by CaiJimmy** [comment]
> @CaiJimmy May I ask why you merged this on master? The point of a PR is to propose that a new branch is merged into master. Merging that proposed branch on master inside the PR seems to go against that idea. Perhaps you intended to rebase?
> 
> image
> 
> The PR is based on code from commit [4272da7](https://github.com/CaiJimmy/hugo-theme-stack/commit/4272da7ee402b43fab957cf328e622279168354c) from December 2022. If it was rebased, the history would be linear. Now the history is non-linear, and the gif below shows what non-linearity means:
> 
> non-linear-history-demonstration [ non-linear-history-demonstration ](https://private-user-images.githubusercontent.com/668724/310335966-694648d7-337f-4d31-988f-b1df70a6f074.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTM0ODYsIm5iZiI6MTcwOTcxMzE4NiwicGF0aCI6Ii82Njg3MjQvMzEwMzM1OTY2LTY5NDY0OGQ3LTMzN2YtNGQzMS05ODhmLWIxZGY3MGE2ZjA3NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwODE5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWEyMjVkYjMzZWEwZDlmYzg1ZDBmMGRjYWYwZmM5ZTRlOTA0NzM0ZTFkNjEzOGI1NDUyNzY3MzcwMDBiNjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UVs7Nkx5_98rT4VteP1-UQf6QeqVtE90VvvF827d6f0) [ ](https://private-user-images.githubusercontent.com/668724/310335966-694648d7-337f-4d31-988f-b1df70a6f074.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTM0ODYsIm5iZiI6MTcwOTcxMzE4NiwicGF0aCI6Ii82Njg3MjQvMzEwMzM1OTY2LTY5NDY0OGQ3LTMzN2YtNGQzMS05ODhmLWIxZGY3MGE2ZjA3NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwODE5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWEyMjVkYjMzZWEwZDlmYzg1ZDBmMGRjYWYwZmM5ZTRlOTA0NzM0ZTFkNjEzOGI1NDUyNzY3MzcwMDBiNjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UVs7Nkx5_98rT4VteP1-UQf6QeqVtE90VvvF827d6f0)

I did this because GitHub says "This branch is out of date with the base branch", so I clicked the button to update the branch to the latest version of the base branch. Is this a bad practice?

**Comment by CaiJimmy** [comment]
> also that I should use webm instead of animated gifs

@ottok I believe this is not currently supported by Hugo (https://github.com/gohugoio/hugo/issues/10030). You'll have to do the transformation manually with another tool.

**Comment by provos** [comment]
Thanks for working on this. I have unfortunately been too busy to help here.

**Comment by ottok** [comment]
> > @CaiJimmy May I ask why you merged this on master? The point of a PR is to propose that a new branch is merged into master. Merging that proposed branch on master inside the PR seems to go against that idea. Perhaps you intended to rebase?
>
> I did this because GitHub says "This branch is out of date with the base branch", so I clicked the button to update the branch to the latest version of the base branch. Is this a bad practice?

Does the [button](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch) offer to do a rebase instead of a merge? How is your project configured? You know the concepts of linear history ("git fast-forward") and merge vs rebase, right?

image

**Comment by ottok** [comment]
Thanks @provos for responding. This idea seems cool, however I can't get it working neither using the original version or any successive version, and there are too many conflicting changes so I can't get it working even when manually trying to apply the patch.

Could you rebase this on latest upstream 'master' branch and then as for re-review and testing? Thanks

**Pull request closed without merging**
