### PR TITLE
Preview

### PR DESCRIPTION
**Pull request by prayashkrsaha**

### CODE REVIEW

**Comment by ElastiCourse** [comment]
Looks good, but this is your main site. What you need is to clone this repo locally on your PC, or fork it to your github account. A PR in this repo would be for the base code with no user customization.

Also keep in mind your blog has very low lighthouse (speed index) score:


I suggest you either
1. Enable image processing in hugo.yaml for both cover, and article
2. Convert images to next-gen format (webp for example)

Good luck

**Comment by prayashkrsaha** [comment]
Thanks for the reply.
Actually I need help in using the Decap CMS. Previously I was using
forestry cms with my blog but now it is decommissioned.
I will be highly obliged if you can help me integrate the cms in blog.
Thanks and regards
Prayash

**Comment by ElastiCourse** [comment]
It looks like you have done most of the work already. I see static/admin folder with the two needed files. You are already on Netlify so that makes things easier. But there could be an issue in `static/admin/config.yml`

I think `public_folder: "/images/uploads"` should be `public_folder: "images/uploads"` compared to starter kit.

Try to access your admin panel https://bawali.netlify.app/admin

Remember to use Netlify Identity for admin login, not your regular Netlify account. Assuming you have followed the steps in the official [guide](https://decapcms.org/docs/hugo/), you should have received an email that says `You have been invited`, from there you click the link to create your login password for the admin panel. 

I tried Decap CMS after reading your comment using the starter kit, not this theme. I'm not in favor of using this frontend for many reasons:
1. It's very limited when it comes to customization. Not many options are available in this GUI, including 99% of frontmatter customization (Aliases, keywords, category, tableofcontent on/off, license on/off.. etc). 
2. Site config only shows what is already in the hugo.yaml, with no option to add any extra options. That means you need to do manually edit config files to customize your site anyway.
3. It doesn't show you a link when you create a post, or even a static link to your website.
4. The deployment takes 1-3 minutes, while hugo vanilla build takes about 20 seconds (This will drain your Netlify build minutes if you post a lot).
5. It's already throwing errors from day 1:

netlift
error2


IMO the Decap will complicate things more, and you will hardly learn anything new about hugo and how to customize it to your liking. 
- If you are looking for a blogging platform with GUI and everything made easier, try wordpress.com.
- If you want to continue using Hugo, I suggest using VS code to write your markdown. All the features in Decap are included and then some. Post previews are one click away. It also scrolls automatically as you write longer posts. Extensions give you unlimited opportunity to play with code including spell checking and SVG previews.

vs0

vs

**Comment by prayashkrsaha** [comment]
Thanks, I'll check it out!

**Pull request closed without merging**
