### PR TITLE
Fix categories with special char or spaces not displayed correctly

### PR DESCRIPTION
**Pull request by romainx**
Hello,

Here is a small fix to call [`urlize`](https://gohugo.io/functions/urlize/) to get the category URL instead of using its name directly. Before this fix it was not working with categories containing special character or white spaces.

Best.

### CODE REVIEW

**Comment by CaiJimmy** [comment]
Hi,

Thanks for the PR 😀

However, this fix brokes support for CJK languages. Example Markdown Front Matter:
```
categories:
    - 测试
    - Test Tag
```

Before the patch:
image

After the patch:
image

I think I just found a better solution: use `Page.GetTerm` function introduced in Hugo 0.65: [Example: List Tags in a Single Page Template](https://gohugo.io/templates/taxonomy-templates/#example-list-tags-in-a-single-page-template). There's no compatibility issue as this theme requires at least Hugo v0.74.

The same issue is present in **tag cloud widget** and the tag list at the end of the article.

https://github.com/CaiJimmy/hugo-theme-stack/blob/809fa7860d678040dc8b3645bdd8ee1beef64b51/layouts/partials/widget/tag-cloud.html#L11

https://github.com/CaiJimmy/hugo-theme-stack/blob/809fa7860d678040dc8b3645bdd8ee1beef64b51/layouts/partials/article/components/tags.html#L5

Would you like to modify the patch? I've got some free time this weekend, so I could also take care of it.

**Comment by romainx** [comment]
Hello @CaiJimmy,

Thank you for the tip. I've implemented the fix for both categories and tags.
I've made a modification in the [example site](whitespace) to add a case with withespaces. 
Looks good. Let me know if it's OK for you.

Best.

**Review by CaiJimmy — APPROVED** [review]
LGTM 😀

**Comment by CaiJimmy** [comment]
Hi @romainx ,

Thanks for the patch 😀

_Just in case, I added a CJK taxonomy to example site article._

**Pull request merged**
