### PR TITLE
fix(comment): moved waline `placeholder` parameter to `locale.placeholder`

### PR DESCRIPTION
**Pull request by L-Super**
1. fix placeholder location
2. update url

reference: https://waline.js.org/en/cookbook/customize/locale.html

### CODE REVIEW

**Comment by L-Super** [comment]
By the way, It seems that there is no `visitor` .

**Review by CaiJimmy — APPROVED** [review]
Thanks!

**Comment by CaiJimmy** [comment]
> By the way, It seems that there is no `visitor` .

Yes, that must have been removed as well. If you find out what the new key of this option is, please open a new PR.

**Comment by L-Super** [comment]
> > By the way, It seems that there is no `visitor` .
> 
> Yes, that must have been removed as well. If you find out what the new key of this option is, please open a new PR.

The change seems to be a bit big, it can't simply implement the corresponding function through add and delete key. So, can you fix it? @CaiJimmy 
refer:
https://waline.js.org/en/guide/features/pageview.html

https://waline.js.org/en/guide/features/comment.html

**Comment by CaiJimmy** [comment]
Actually, there's a bigger issue: the current version of Waline included within this theme is `v2`: https://github.com/CaiJimmy/hugo-theme-stack/blob/4948a3723e42fb775f4d895e4d173c5521be81b9/layouts/partials/comments/provider/waline.html#L1-L2

**Comment by L-Super** [comment]
> Actually, there's a bigger issue: the current version of Waline included within this theme is `v2`:
> 
> https://github.com/CaiJimmy/hugo-theme-stack/blob/4948a3723e42fb775f4d895e4d173c5521be81b9/layouts/partials/comments/provider/waline.html#L1-L2

Could you upgrade to the latest version?

**Comment by CaiJimmy** [comment]
> > Actually, there's a bigger issue: the current version of Waline included within this theme is `v2`:
> > https://github.com/CaiJimmy/hugo-theme-stack/blob/4948a3723e42fb775f4d895e4d173c5521be81b9/layouts/partials/comments/provider/waline.html#L1-L2
> 
> Could you upgrade to the latest version?

No, I don't use Waline and can't test if there are any compatibility issues with v3.

**Pull request merged**
