### PR TITLE
feat: change the page vertical scrollbar styles

### PR DESCRIPTION
**Pull request by moll-y**
This change will make the _vertical_ scrollbar to follow the dark and light style modes. Also, this change will make the _vertical_ scrollbar to look consistent in both, Chromium and Firefox. 

I know we had to set the vertical scrollbar (```html { overflow-y: scroll; ...}```), even when a page doesn't have too much content to need one, to make sure the layout doesn't change when one is switching between pages. For example, in the Search page, when the search form is empty (so it doesn't need a vertical scrollbar because there is no content beyond the vertical viewport), the vertical scrollbar is still there. This change will hide that behavior as well.

### CODE REVIEW

**Comment by CaiJimmy** [comment]
Thanks for the PR!

I might take some time before merging this. Because my development environment is filled with customized styles, and I have to delete them / commit them into the master branch before looking into this.

May I know why you have moved `[data-scheme="dark"]` outside of `:root` block? It doesn't work if it's inside?

**Comment by moll-y** [comment]
> May I know why you have moved `[data-scheme="dark"]` outside of `:root` block? It doesn't work if it's inside?

Yes, it doesn't work if we place it inside of  `:root`. I think it's because of the precedence rules of CSS.

**Comment by CaiJimmy** [comment]
I just checked the MDN doc: https://developer.mozilla.org/en-US/docs/Web/CSS/:root

> :root represents the <html> element and is identical to the selector html, except that its specificity is higher.

`[data-scheme="dark"]` can still be contained inside `:root`, we just have to add `&` before its selector, to indicate that it applies to `:root`.

**Comment by CaiJimmy** [comment]
Seems to work well after adding the above fix 👌

**Comment by CaiJimmy** [comment]
I was wondering if we could **apply this scrollbar style across all elements**, by moving it out from `html` selector. Since it's the same style for horizontal scrollbar:

https://github.com/CaiJimmy/hugo-theme-stack/blob/495a3b0289797ef675d2d7befa1362a07e7f6bdd/assets/scss/partials/layout/list.scss#L55-L71

**Review by CaiJimmy — APPROVED** [review]

**Comment by CaiJimmy** [comment]
I submitted a patch to make custom scrollbar style available for all elements. Now the code block and sidebar menu scrollbar are also styled. 

It will be necessary to make some adjustments to the scrollbar color on dark mode, especially for code blocks:

image

But I'll merge this for now. Thanks for the PR 👍

**Comment by moll-y** [comment]
> I just checked the MDN doc: https://developer.mozilla.org/en-US/docs/Web/CSS/:root
> 
> > :root represents the  element and is identical to the selector html, except that its specificity is higher.
> 
> `[data-scheme="dark"]` can still be contained inside `:root`, we just have to add `&` before its selector, to indicate that it applies to `:root`.

That's kinda interesting, I will take note.

**Comment by moll-y** [comment]
> I was wondering if we could **apply this scrollbar style across all elements**, by moving it out from `html` selector. Since it's the same style for horizontal scrollbar:
> 
> https://github.com/CaiJimmy/hugo-theme-stack/blob/495a3b0289797ef675d2d7befa1362a07e7f6bdd/assets/scss/partials/layout/list.scss#L55-L71

I think we could just leave it in html and remove it from the other elements. Scrollbar styles are something our target elements can inherit.

**Comment by moll-y** [comment]
> It will be necessary to make some adjustments to the scrollbar color on dark mode, especially for code blocks:

Yes, I agree. 

By the way, I was using this color:  `--scrollbar-thumb: hsl(0, 0%, 30%);`. You could check it out, it seems to looks good, but I don't know, I think you are better taste than me.

**Comment by moll-y** [comment]
> But I'll merge this for now. Thanks for the PR +1

Thanks to you too.

**Pull request merged**
