### PR TITLE
fix: incorrect image & menu path for site hosted in subdir

### LINKED ISSUE #152: Image path is incorrect
**Describe the bug**
After I add the image and publish it, I found that in some html files, the path of the images are incorrect.

I add the image to the path "/public/p/deep-learning-1-activation-function/deep-learning-1-activation-function".

After publishing to github, the file was uploaded to the path "https://ZihaoLin0123.github.io/p/deep-learning-1-activation-function/helena-hertz-wWZzXlDpMog-unsplash.jpg". 

However, in some html files, the image path is "p/deep-learning-1-activation-function/helena-hertz-wWZzXlDpMog-unsplash.jpg" which miss the base url. 

How can I fix this?

**Screenshots**

Please see the details here:

751613951321_ pic_hd

### PR DESCRIPTION
**Pull request by CaiJimmy**
closes #152

### CODE REVIEW

**Comment by MattDaines** [comment]
Not 100% sure it's this PR but pages don't seem to be navigating properly anymore.

Some examples:

Home --> About = ./about
Home --> Search = ./search

Nothing wrong with those. But going from page to page we end up with a 404 because:

About --> About = ./about/about
About --> Search = ./about/search

**Comment by CaiJimmy** [comment]
Thanks for reporting. 

It's caused by this PR definitely. I'll try to fix it.

**Comment by CaiJimmy** [comment]
Can you please tell me how you added those menu items? In case of `config.yaml` please paste `menu` section of it.

**Comment by MattDaines** [comment]
Yep, it's through `config.yaml`.

```yaml
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search
```

**Comment by CaiJimmy** [comment]
Two ways to solve this:

1. Add slash before url, `search` -> `/search`
2. Add menu item using frontmatter method: https://github.com/CaiJimmy/hugo-theme-stack/pull/167

**Comment by MattDaines** [comment]
Yep, that did it! Opted for option 1 for now. Given 2 is the recommended method in [your documentation](https://docs.stack.jimmycai.com/configuration/custom-menu) I'll update my site in the near future.

Thanks for your help, again!

**Pull request merged**
