### PR TITLE
fix(sidebar): improve accessibility of sidebar bottom menu

### PR DESCRIPTION
**Pull request by TheJiahao**
- Move `<div class="menu-bottom-section">` outside `<ol class="menu" id="main-menu">` to fix warning `<li> elements must be contained in a <ul> or <ol>`

- Add `title="language"` to language select menu to fix error `Select element must have an accessible name: Element has no title attribute`

The appearance is identical after change.

Before:
before

After:
after

### CODE REVIEW

**Comment by ottok** [comment]
This makes sense and would fix issues that even [PageSpeed accessibility check](https://pagespeed.web.dev/analysis/https-optimizedbyotto-com/4d9xezjgdt) complains about:

image

**Comment by ottok** [comment]
Note that #950 is targeting the same section of code, so once either one is merged, the other one needs to be rebased.

**Review by CaiJimmy — APPROVED** [review]
Thanks!

**Comment by cubercsl** [comment]
@TheJiahao Could you confirm this change works fine in mobile size? I tried to cherry-pick this change to v4 branch, it does not work.

**Comment by TheJiahao** [comment]
@cubercsl I can confirm that the bottom menu including language and theme switch is not showing in mobile. This will be fixed in PR #966.

**Pull request merged**
