### PR TITLE
Add og:title tag option.

### PR DESCRIPTION
**Pull request by MofuMoca**
More introduction in commit comment.
TL;DL
Add an option to choose og:title will be "Title" or "Title - SiteName".

### CODE REVIEW

**Comment by CaiJimmy** [comment]
Thanks for the PR! And sorry for the late reply 🙏.

For sites that respect the OpenGraph standard and display `og:site`, would this feature cause the site title to appear twice if it's enabled?

**Comment by ottok** [comment]
Should you perhaps use `git rebase -i` to squash the two commits into one and write the commit message in English?

**Comment by MofuMoca** [comment]
> Thanks for the PR! And sorry for the late reply 🙏.
> 
> For sites that respect the OpenGraph standard and display `og:site`, would this feature cause the site title to appear twice if it's enabled?

Yes and no. But I think this will not be a bad side effect.

There are some use case for me.
image
At plurk.com will not show og:site_name.

image
Here are mastodon.

image
FaceBook will show URL instand of og:site_name.

image
Finally discord is similar to mastodon.



> Should you perhaps use `git rebase -i` to squash the two commits into one and write the commit message in English?

Thank for advice. I will do rebase later if my PR has been accept ,should I recreate a new PR?
And the commit message I write down in English after Chinese.
There are the same context.

**Comment by ottok** [comment]
Thanks for the clarifying pictures.

If you change the code or commits, you should *not* open a new PR but
simply update this one with git push or git --force push.

**Comment by ottok** [comment]
I am not sure if this is needed? At least on my site the title for front page and for posts works correctly as expected:

[Front page](https://optimizedbyotto.com/): `<meta property='og:title' content='Optimized by Otto'>`

[Post page:](https://optimizedbyotto.com/post/git-commit-message-examples/) `<meta property='og:title' content='Learn to write better git commit messages by example'>`

**Comment by CaiJimmy** [comment]
> I am not sure if this is needed? At least on my site the title for front page and for posts works correctly as expected:
> 
> [Front page](https://optimizedbyotto.com/): `<meta property='og:title' content='Optimized by Otto'>`
> 
> [Post page:](https://optimizedbyotto.com/post/git-commit-message-examples/) `<meta property='og:title' content='Learn to write better git commit messages by example'>`

@ottok The problem is that some sites do not read `og:site_name` and use only `og:title`. Adding this feature forces the site title to be included in `og:title`.

But in my opinion this is a really rare use case and would affect sites that respect the OpenGraph standard. Besides, this fix can be achieved by overriding the template. So I'm going to reject this PR. Sorry @MofuMoca for taking so long to decide 🙏 .

**Pull request closed without merging**
