### PR TITLE
feat(i18n): add Hindi translation

### PR DESCRIPTION
**Pull request by amanr-dev**
Add Hindi translation for Hindi speakers and it's my native language.

### CODE REVIEW

**Comment by amanr-dev** [comment]
Hi @CaiJimmy, Please review the pull request.

**Comment by amanr-dev** [comment]
Hi @CaiJimmy, Please review the pull request. I added Hindi language translation for Hindi speakers.

**Review by CaiJimmy — APPROVED** [review]
Thanks!

(Sorry, I wasn't able to review this PR during the week due to my coursework)

**Comment by amanr-dev** [comment]
> Thanks!
> 
> (Sorry, I wasn't able to review this PR during the week due to my coursework)

It's Ok👍

**Pull request merged**
