### PR TITLE
fix: anchor link need decode

### PR DESCRIPTION
**Pull request by GGXXLL**
Anchor links need to be decoded when using Chinese. Otherwise, the targetId-element cannot be found.

### CODE REVIEW

**Comment by CaiJimmy** [comment]
Thanks for the PR and sorry for the delay.

I'm not able to reproduce the issue using Chrome Dev (_the targetId-element cannot be found._) using Chrome 109. Could you indicate please the browser in which this issue is present?

**Comment by GGXXLL** [comment]
Hello, my chrome version is 107.0.5304.107 and after I upgrade to 108.0.5359.95 it still reproducible. I didn't try 109.

**Comment by CaiJimmy** [comment]
Could you provide an example page / Markdown file for me to reproduce it?

**Comment by GGXXLL** [comment]
Multiple newlines to observe displacement
```
---
title: 'Example'
tags:
date: '2022-12-03'
categories:
draft: false
---

## 你好

&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  
&  

[jump](#你好)
```

**Comment by cubercsl** [comment]
[heading link render hook](https://gohugo.io/templates/render-hooks/#heading-link-example) with chinese also can't work correctly without this patch.

**Review by CaiJimmy — APPROVED** [review]

**Comment by CaiJimmy** [comment]
Thanks! I though the problem was related to the table of contents.

**Pull request merged**
