### PR TITLE
fix(i18n/ru): fix typo in 'notFound'

### PR DESCRIPTION
**Pull request by sot-tech**

### CODE REVIEW

**Comment by CaiJimmy** [comment]
Thanks for your contribution!

Can I know why you added "_numbered translation to 'subsection'_"? Is that something related to Russian grammar? Because in the translation of the rest of languages numbers are not included, just to keep it uniform.

**Comment by sot-tech** [comment]
> Thanks for your contribution!
> 
> Can I know why you added "_numbered translation to 'subsection'_"? Is that something related to Russian grammar? Because in the translation of the rest of languages numbers are not included, just to keep it uniform.

Hello. Correction for `subsections` is optional (until recently, I did not figure out exactly where the translation is used, my fault).
Numbers was added for the internal portal, and I just wanted to share it. 
I think in many cases this translation could be used:
```
list:
    subsection:
        one: Подраздел
        other: Подразделы
...
```
Important: Подраздел**ы** for any plural.
If needed, i'll modify it.

However, fixes `notFound.title.other` and `footer.designedBy.other` are primary.

**Comment by CaiJimmy** [comment]
I think it's better just to keep it without numbers for now. Can you please modify it? 

Thanks in advance.

**Comment by sot-tech** [comment]
> I think it's better just to keep it without numbers for now. Can you please modify it?
> 
> Thanks in advance.

Done. Also did not remove `few` and `many` lines, because of _hugo_ warnings, and cnanged `section` line to fully match the English sample.

**Comment by CaiJimmy** [comment]
Thanks! 

I removed `archives.categories` string because it is no longer being used (#108)

**Pull request merged**
