### PR TITLE
fix(sidebar): add `padding-bottom` to the right sidebar

### PR DESCRIPTION
**Pull request by cmpute**
改动之后滑到页面底部时右侧边栏底部会有足够的留白

### CODE REVIEW

**Review by CaiJimmy — APPROVED** [review]
Thanks!

**Comment by mathisgauthey** [comment]
How to get this change to prevent the overflow from right sidebar ? Is there an update to run or something ?

**Comment by CaiJimmy** [comment]
> How to get this change to prevent the overflow from right sidebar ? Is there an update to run or something ?

@mathisgauthey It should be available now. Run `hugo mod get -u github.com/CaiJimmy/hugo-theme-stack/v3` to update manually if you are using Hugo module.

**Comment by mathisgauthey** [comment]
Actually I don't understand. There seems to be 3 ways to install the plugin :
- quick start
- git submodule
- Hugo module

I started with quick start but icons are not working for favicon.

Hence as I heard you're not going to keep the theme up any longer, I decided to use git submodule. But can't figure how to make this work. Guess I still have much to learn 👌

**Pull request merged**
