### PR TITLE
feat(article): reading time

### PR DESCRIPTION
**Pull request by uluumbch**
adding feature reading time #201.
i've changed the icon for date published to date.svg icon and reading time to time.svg
image
also added reading time in archive page
image

### CODE REVIEW

**Review by srinidhibhat45 — COMMENTED** [review]
Works like a charm! thank you

**Comment by MikDal002** [comment]
Are there any plans to merge it with main branch?

**Comment by CaiJimmy** [comment]
Sorry, I totally forgot to reply to this. Thanks to @uluumbch for the PR. 👍

> Are there any plans to merge it with main branch?
@MikDal002 
Not yet, sorry. I'm not sure if this should be integrated into this theme 😓.

**Comment by MikDal002** [comment]
Maybe with a flag? If you are not sure, then let decide the user :).

**Comment by jantaylor** [comment]
@CaiJimmy What if it was shown/enabled when `.ReadingTime` is there? That gives the user a choice and maintains BWC.

**Pull request merged**
