### PR TITLE
fix: head.html keywords parameter does not take effect

### PR DESCRIPTION
**Pull request by L-Super**

### CODE REVIEW

**Comment by ottok** [comment]
The keywords are supposed to come from the Front Matter tags, e.g.:

```
---
title: How to code 10x faster than an average programmer
date: 2023-01-29
keywords:
  - Entr
  - Atom
  - Pulsar
  - software quality
  - development velocity
  - developer productivity
```

This already work correctly. Your change would make every single page show the exact same keywords based on a site-wide configuration. I don't think that is how meta keywords should work?

**Comment by L-Super** [comment]
> The keywords are supposed to come from the Front Matter tags, e.g.:
> 
> ```
> ---
> title: How to code 10x faster than an average programmer
> date: 2023-01-29
> keywords:
>   - Entr
>   - Atom
>   - Pulsar
>   - software quality
>   - development velocity
>   - developer productivity
> ```
> 
> This already work correctly. Your change would make every single page show the exact same keywords based on a site-wide configuration. I don't think that is how meta keywords should work?

My mistake, I originally wanted to fix the absence of the keywords parameter in index.html, which affects SEO. So are there other ways to solve this?

**Comment by ottok** [comment]
If you put this `keywords:` in your blog post, you will have in `example.com/post/title/index.html` the meta keywords.

According to Google they don't read the `<meta keywords="">` stuff anymore, so this does not actually help with SEO and most modern sites don't use it. You would be better off reading about schema.org semantic markup, adding a custom `layouts/partials/head/custom.html` to your site,  and testing with https://developers.google.com/search/docs/appearance/structured-data.

**Comment by CaiJimmy** [comment]
> So are there other ways to solve this?

Technically, the homepage is just a special kind of page, hence it's possible to add frontmatter to it.

Try creating a `content/_index.md` file, with the following content:

```markdown
---
keywords:
  - test
  - test2
---
```

**Comment by L-Super** [comment]
> <meta keywords="">

Thanks a lot

**Comment by L-Super** [comment]
> If you put this `keywords:` in your blog post, you will have in `example.com/post/title/index.html` the meta keywords.
> 
> According to Google they don't read the `<meta keywords="">` stuff anymore, so this does not actually help with SEO and most modern sites don't use it. You would be better off reading about schema.org semantic markup, adding a custom `layouts/partials/head/custom.html` to your site, and testing with https://developers.google.com/search/docs/appearance/structured-data.

Thanks a lot

**Pull request closed without merging**
