### PR TITLE
feat: sticky sidebar

### PR DESCRIPTION
**Pull request by CaiJimmy**
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/236

### CODE REVIEW

**Comment by CaiJimmy** [comment]
I have not merged this yet because I would like to find an alternative script that's not GPL licensed, just in the case that this theme changes the license into MIT in the future.

**Comment by CaiJimmy** [comment]
After trying many other plugins, the result still does not convince me (feels buggy). 

I'll leave this for now.

**Comment by MikDal002** [comment]
Maybe could you add this feature as experimental and let other users test it? :)

**Comment by CaiJimmy** [comment]
> Maybe could you add this feature as experimental and let other users test it? :)

You can `checkout` this branch and test it. I won't merge this since it doesn't work as I expected.

**Pull request closed without merging**
