### PR TITLE
refactor(opengraph/twitter): add @ before username

### PR DESCRIPTION
**Pull request by zhixuan666**
config文件无法输入`@`

### CODE REVIEW

**Comment by CaiJimmy** [comment]
image

加双引号可以输入

**Comment by zhixuan666** [comment]
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html

**Comment by CaiJimmy** [comment]
谢谢！

**Comment by zhixuan666** [comment]
😮

**Pull request merged**
