### PR TITLE
fix(comments): update Remark42 source code

### PR DESCRIPTION
**Pull request by paskal**
Updated (Remark42) frontend code taken from https://remark42.com/docs/configuration/frontend/.

Discrepancy discovered in https://github.com/umputun/remark42/discussions/1483.

### CODE REVIEW

**Comment by paskal** [comment]
cc @CaiJimmy, could you please review my PR?

**Comment by CaiJimmy** [comment]
> cc @CaiJimmy, could you please review my PR?

Sorry, I won't be able to process any of the PRs soon due to college tasks 😥.

**Review by CaiJimmy — APPROVED** [review]
Thanks!

**Comment by CaiJimmy** [comment]
Thanks for the fix!

(And sorry for taking this long to merge it 🙏)

**Pull request merged**
