### PR TITLE
fix(article): margin collapsing in code block (firefox)

### PR DESCRIPTION
**Pull request by simbafs**
# Describe the problem
When enable line number in codeblock, margin collapsing happens in single line code block. cause the problem in the following image. 

圖片

# How to solve it
Add `display: block;` to `.lnt` in `assets/scss/partials/highlight/common.scss`

### CODE REVIEW

**Comment by CaiJimmy** [comment]
Sorry for the late reply and thanks for the PR!

Could you please paste the sample code block here? I don't fully understand the problem and can't reproduce it.

**Comment by simbafs** [comment]
Start with [https://github.com/CaiJimmy/hugo-theme-stack-starter](https://github.com/CaiJimmy/hugo-theme-stack-starter), adding this patch
```
From 3b5c7d02a57cdb6f50fd85ab0de1add080d7f068 Mon Sep 17 00:00:00 2001
From: SimbaFs <simba.fs@gmail.com>
Date: Sun, 3 Sep 2023 10:17:44 +0800
Subject: [PATCH] margin-collapse

---
 assets/jsconfig.json | 10 ++++++++++
 content/post/test.md | 20 ++++++++++++++++++++
 2 files changed, 30 insertions(+)
 create mode 100644 assets/jsconfig.json
 create mode 100644 content/post/test.md

diff --git a/assets/jsconfig.json b/assets/jsconfig.json
new file mode 100644
index 0000000..f7d6729
--- /dev/null
+++ b/assets/jsconfig.json
@@ -0,0 +1,10 @@
+{
+ "compilerOptions": {
+  "baseUrl": ".",
+  "paths": {
+   "*": [
+    "../../hugo_cache_simba/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.19.0/assets/*"
+   ]
+  }
+ }
+}
\ No newline at end of file
diff --git a/content/post/test.md b/content/post/test.md
new file mode 100644
index 0000000..bbf1b45
--- /dev/null
+++ b/content/post/test.md
@@ -0,0 +1,20 @@
+---
+title: "Test"
+description: 
+date: 2023-09-03T10:14:52+08:00
+image: 
+math: 
+license: 
+hidden: false
+comments: true
+---
+
+```
+one line code block
+```
+
+```
+two line code block
+two line code block
+```
+
-- 
2.34.1
```
than you can see the problem at [http://localhost:1313/p/test/](http://localhost:1313/p/test/), like this 
圖片

**Comment by CaiJimmy** [comment]
Thank you very much! I just replicated the issue with Firefox. Chrome is not affected by this issue.

**Review by CaiJimmy — APPROVED** [review]

**Comment by simbafs** [comment]
Oh, I never thought it would vary from browser to browser xddd

**Pull request merged**
