### PR TITLE
chore: bump Twikoo front-end to latest released version `1.6.39`

### PR DESCRIPTION
**Pull request by gvoze32**
This PR bumps Twikoo front-end to latest released version 1.6.34.

### CODE REVIEW

**Review by gvoze32 — COMMENTED** [review]
Update Twikoo Front-End to 1.6.35

**Comment by gvoze32** [comment]
Update Twikoo Front-End to 1.6.38

**Comment by gvoze32** [comment]
Update Twikoo Front-End to 1.6.39

**Review by CaiJimmy — APPROVED** [review]
Thanks!

**Pull request merged**
